#!/bin/bash
# Script to print all deployment secrets for easy copying

echo "=== COPY THESE VALUES TO DEPLOYMENT SECRETS ==="
echo ""
echo "1. DATABASE_URL"
echo "$DATABASE_URL"
echo ""
echo "2. SUPABASE_URL"
echo "$SUPABASE_URL"
echo ""
echo "3. SUPABASE_SERVICE_KEY"
echo "$SUPABASE_SERVICE_KEY"
echo ""
echo "4. SUPABASE_ANON_KEY"
echo "$SUPABASE_ANON_KEY"
echo ""
echo "5. VITE_FIREBASE_API_KEY"
echo "$VITE_FIREBASE_API_KEY"
echo ""
echo "6. VITE_FIREBASE_APP_ID"
echo "$VITE_FIREBASE_APP_ID"
echo ""
echo "7. VITE_FIREBASE_PROJECT_ID"
echo "$VITE_FIREBASE_PROJECT_ID"
echo ""
echo "8. SERPAPI_API_KEY"
echo "$SERPAPI_API_KEY"
echo ""
echo "9. ROBOFLOW_API_KEY"
echo "$ROBOFLOW_API_KEY"
echo ""
echo "10. SESSION_SECRET"
echo "$SESSION_SECRET"
echo ""
echo "=== END OF SECRETS ==="
